const app=document.getElementById("app"),title=document.getElementById("title");
let records=[
{id:"PR-2026-041",category:"Medical Equipment",owner:"Central Procurement",status:"Approval pending",value:"Demo value",submitted:"03 Oct 2026"},
{id:"PR-2026-038",category:"Medicines",owner:"Clinical Supplies",status:"Tender ready",value:"Demo value",submitted:"02 Oct 2026"},
{id:"PR-2026-035",category:"Laboratory Supplies",owner:"Diagnostics",status:"Under review",value:"Demo value",submitted:"01 Oct 2026"},
{id:"PR-2026-031",category:"IT Equipment",owner:"Digital Services",status:"Exception",value:"Demo value",submitted:"29 Sep 2026"}
];
let events=[
["Approval requested","PR-2026-041 · Procurement Controller · 11:42"],
["Specification updated","PR-2026-038 · Procurement Analyst · 10:18"],
["Exception created","PR-2026-031 · Compliance Review · 09:37"]
];
const steps=["Draft","Under review","Approval pending","Tender ready","Award ready"];
function badge(s){const c=s==="Tender ready"||s==="Award ready"?"ok":s==="Approval pending"||s==="Exception"?"warn":"";return '<span class="pill '+c+'">'+s+"</span>"}
function overview(){app.innerHTML='<div class="grid"><div class="card"><div class="label">Open requests</div><div class="num">'+records.length+'</div></div><div class="card"><div class="label">Pending approvals</div><div class="num">'+records.filter(x=>x.status==="Approval pending").length+'</div></div><div class="card"><div class="label">Tender ready</div><div class="num">'+records.filter(x=>x.status==="Tender ready").length+'</div></div><div class="card"><div class="label">Open exceptions</div><div class="num">'+records.filter(x=>x.status==="Exception").length+'</div></div></div><div class="layout"><div class="card"><div class="card-head"><h2>Recent requests</h2><span class="muted">Synthetic data</span></div>'+records.map((x,i)=>'<div class="row"><div><button class="action" data-open="'+i+'"><strong>'+x.id+'</strong></button><div class="muted">'+x.category+' · '+x.owner+'</div></div>'+badge(x.status)+'</div>').join("")+'</div><div class="card"><h2>Workflow today</h2><div class="row"><span>Validation</span><strong>6</strong></div><div class="row"><span>Review</span><strong>5</strong></div><div class="row"><span>Approval</span><strong>4</strong></div><div class="row"><span>Exception</span><strong>2</strong></div></div></div>';bindOpen()}
function table(view){let rows=view==="requests"?records:view==="approvals"?records.filter(x=>x.status.includes("Approval")):records.filter(x=>x.status.includes("Exception"));app.innerHTML='<div class="card"><div class="card-head"><h2>'+title.textContent+'</h2><span class="muted">'+rows.length+' records</span></div><table class="table"><thead><tr><th>Reference</th><th>Category</th><th>Owner</th><th>Status</th><th></th></tr></thead><tbody>'+rows.map(x=>{const i=records.indexOf(x);return '<tr><td><button class="action" data-open="'+i+'"><strong>'+x.id+'</strong></button></td><td>'+x.category+'</td><td>'+x.owner+'</td><td>'+badge(x.status)+'</td><td><button class="action" data-open="'+i+'">Open</button></td></tr>'}).join("")+'</tbody></table></div>';bindOpen()}
function bindOpen(){document.querySelectorAll("[data-open]").forEach(b=>b.onclick=()=>detail(Number(b.dataset.open)))}
function detail(i){const x=records[i],current=steps.indexOf(x.status),safeCurrent=current<0?1:current,next=safeCurrent<steps.length-1?steps[safeCurrent+1]:null;title.textContent=x.id;app.innerHTML='<div class="layout"><div class="card"><p class="eyebrow">REQUEST DETAIL</p><h2>'+x.category+'</h2><div class="row"><span>Owner</span><strong>'+x.owner+'</strong></div><div class="row"><span>Submitted</span><strong>'+x.submitted+'</strong></div><div class="row"><span>Status</span>'+badge(x.status)+'</div><div class="row"><span>Commercial data</span><span class="muted">'+x.value+'</span></div><div class="workflow"><div class="workflow-title">Workflow</div><div class="steps">'+steps.map((s,n)=>'<span class="'+(n<safeCurrent?"done ":n===safeCurrent?"current ":"")+'">'+s+'</span>').join("")+'</div></div><div class="checks"><strong>Readiness checks</strong><label><input type="checkbox" checked> Requirement complete</label><label><input type="checkbox" checked> Specification reviewed</label><label><input type="checkbox" '+(x.status==="Exception"?"":"checked ")+'> Approval evidence attached</label></div><div class="actions">'+(next?'<button class="primary" id="advance">Move to '+next+'</button>':"")+(x.status==="Exception"?'<button class="secondary" id="resolve">Resolve exception</button>':"")+'<button class="action" id="back">Back</button></div></div><div class="card"><div class="card-head"><h2>Decision history</h2><span class="muted">Audit trail</span></div><div class="timeline">'+events.map(e=>'<div class="event"><strong>'+e[0]+'</strong><div class="muted">'+e[1]+'</div></div>').join("")+'</div></div></div>';if(next)document.getElementById("advance").onclick=()=>{x.status=next;events.unshift(["Workflow advanced",x.id+" · current owner · just now"]);detail(i)};if(document.getElementById("resolve"))document.getElementById("resolve").onclick=()=>{x.status="Under review";events.unshift(["Exception resolved",x.id+" · current owner · just now"]);detail(i)};document.getElementById("back").onclick=overview}
function audit(){app.innerHTML='<div class="card"><div class="card-head"><h2>Recent audit events</h2><span class="muted">Session activity</span></div><div class="timeline">'+events.map(e=>'<div class="event"><strong>'+e[0]+'</strong><div class="muted">'+e[1]+'</div></div>').join("")+'</div></div>'}
function newRequest(){title.textContent="New request";app.innerHTML='<form class="card form" id="requestForm"><div class="notice">Demo form. Submitting creates a local record only.</div><div class="field"><label>Business requirement</label><textarea id="req" required placeholder="Describe the requirement..."></textarea></div><div class="field"><label>Category</label><select id="cat"><option>Medical Equipment</option><option>Medicines</option><option>Laboratory Supplies</option><option>IT Equipment</option></select></div><div class="field"><label>Requesting unit</label><input id="owner" required placeholder="e.g. Central Procurement"></div><button class="primary">Create draft</button></form>';document.getElementById("requestForm").onsubmit=e=>{e.preventDefault();const id="PR-2026-"+String(42+records.length).padStart(3,"0");records.unshift({id,category:document.getElementById("cat").value,owner:document.getElementById("owner").value,status:"Draft",value:"Demo value",submitted:"05 Oct 2026"});events.unshift(["Draft created",id+" · local demo · just now"]);load("requests")}}
function load(v){title.textContent=v==="overview"?"Overview":v[0].toUpperCase()+v.slice(1);v==="overview"?overview():v==="audit"?audit():v==="requests"||v==="approvals"||v==="exceptions"?table(v):overview()}
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("nav button").forEach(x=>x.classList.remove("active"));b.classList.add("active");load(b.dataset.view)});document.getElementById("newBtn").onclick=newRequest;overview();